/** Fetch and generate the gitignored Base16 theme catalog. */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdir, readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "yaml";
import { base16ToPalette, normalizeThemeId, parseBase16Scheme } from "../src/themes/base16";
import type { Palette } from "../src/themes/palettes";

const SOURCE_REVISION = "fdca32a0d14ec80ad83a78a9ccb85592ca6cb9e1";
const SOURCE_REPOSITORY = "https://github.com/tinted-theming/schemes.git";
const SOURCE_BRANCH = "spec-0.11";
const OUT_DIR = path.resolve(import.meta.dir, "../src/generated");
const OUT_FILE = path.join(OUT_DIR, "base16Themes.ts");
const STATE_FILE = path.join(OUT_DIR, ".base16-state.json");
const CACHE_DIR = path.resolve(import.meta.dir, "../.base16-cache");
const SOURCE_DIR = path.join(CACHE_DIR, "source");

function log(message: string): void {
  console.log(`[themes] ${message}`);
}

function isCurrent(): boolean {
  try {
    const state = JSON.parse(readFileSync(STATE_FILE, "utf8")) as { revision?: string };
    return state.revision === SOURCE_REVISION && existsSync(OUT_FILE);
  } catch {
    return false;
  }
}

async function fetchSource(): Promise<void> {
  rmSync(CACHE_DIR, { recursive: true, force: true });
  await mkdir(CACHE_DIR, { recursive: true });
  execFileSync(
    "git",
    ["clone", "--quiet", "--depth", "1", "--branch", SOURCE_BRANCH, "--single-branch", "--no-checkout", SOURCE_REPOSITORY, SOURCE_DIR],
    { stdio: "inherit" },
  );
  try {
    execFileSync("git", ["-C", SOURCE_DIR, "fetch", "--quiet", "--depth", "1", "origin", SOURCE_REVISION], {
      stdio: "inherit",
    });
    execFileSync("git", ["-C", SOURCE_DIR, "checkout", "--quiet", "--detach", SOURCE_REVISION], {
      stdio: "inherit",
    });
  } catch {
    throw new Error(
      `pinned revision ${SOURCE_REVISION} could not be checked out from ${SOURCE_REPOSITORY}`,
    );
  }
}

async function findDirectory(root: string, name: string): Promise<string | null> {
  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const candidate = path.join(root, entry.name);
    if (entry.name === name) return candidate;
    const nested = await findDirectory(candidate, name);
    if (nested) return nested;
  }
  return null;
}

async function sourceRoot(): Promise<string> {
  const root = await findDirectory(SOURCE_DIR, "base16");
  if (!root) throw new Error("Base16 source archive contained no base16 directory");
  return root;
}

async function schemeFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const file = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await schemeFiles(file)));
    } else if (/\.(yaml|yml)$/i.test(entry.name)) {
      files.push(file);
    }
  }
  return files.sort();
}

async function generate(): Promise<void> {
  const root = await sourceRoot();
  const files = await schemeFiles(root);
  if (files.length === 0) throw new Error("Base16 source contains no YAML schemes");

  const palettes: Palette[] = [];
  const ids = new Set<string>();
  for (const file of files) {
    const raw = parse(await readFile(file, "utf8")) as Record<string, unknown>;
    const scheme = parseBase16Scheme(raw);
    const id = normalizeThemeId(scheme.slug ?? path.basename(file, path.extname(file)));
    if (ids.has(id)) throw new Error(`duplicate Base16 theme ID: ${id}`);
    ids.add(id);
    palettes.push(base16ToPalette(id, scheme));
  }

  const source = [
    "// Generated by scripts/fetch-base16-themes.ts — do not edit.",
    `// Source: ${SOURCE_REPOSITORY} @ ${SOURCE_REVISION}`,
    "import type { Palette } from \"../themes/palettes\";",
    "",
    `export const GENERATED_PALETTES: Palette[] = ${JSON.stringify(palettes, null, 2)};`,
    "",
  ].join("\n");
  await mkdir(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, source);
  writeFileSync(STATE_FILE, JSON.stringify({ revision: SOURCE_REVISION, count: palettes.length }, null, 2));
  log(`generated ${palettes.length} Base16 themes`);
}

async function main(): Promise<void> {
  if (isCurrent() && !process.argv.includes("--force")) {
    log("catalog is current — skipping");
    return;
  }
  await fetchSource();
  try {
    await generate();
  } finally {
    rmSync(CACHE_DIR, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error(`[themes] ${error instanceof Error ? error.message : error}`);
  process.exit(1);
});
