/** Fetch and generate the gitignored Base16 theme catalog. */
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdir, readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { extract } from "tar";
import { parse } from "yaml";
import { base16ToPalette, normalizeThemeId, parseBase16Scheme } from "../src/themes/base16";
import type { Palette } from "../src/themes/palettes";

const SOURCE_REVISION = "fdca32a0d14ec80ad83a78a9ccb85592ca6cb9e1";
const SOURCE_URL = `https://codeload.github.com/tinted-theming/schemes/tar.gz/${SOURCE_REVISION}`;
const OUT_DIR = path.resolve(import.meta.dir, "../src/generated");
const OUT_FILE = path.join(OUT_DIR, "base16Themes.ts");
const STATE_FILE = path.join(OUT_DIR, ".base16-state.json");
const CACHE_DIR = path.resolve(import.meta.dir, "../.base16-cache");
const SOURCE_DIR = path.join(CACHE_DIR, "source");
const ARCHIVE_FILE = path.join(CACHE_DIR, "schemes.tar.gz");

function log(message: string): void {
  console.log(`[themes] ${message}`);
}

function isCurrent(): boolean {
  try {
    const state = JSON.parse(readFileSync(STATE_FILE, "utf8")) as { revision?: string };
    return state.revision === SOURCE_REVISION && existsSync(OUT_FILE);
  } catch {
    return false;
  }
}

async function fetchSource(): Promise<void> {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Base16 source download failed (${response.status}) from ${SOURCE_URL}`);
  }
  rmSync(CACHE_DIR, { recursive: true, force: true });
  await mkdir(SOURCE_DIR, { recursive: true });
  writeFileSync(ARCHIVE_FILE, Buffer.from(await response.arrayBuffer()));
  await extract({ cwd: SOURCE_DIR, file: ARCHIVE_FILE });
}

async function sourceRoot(): Promise<string> {
  if (existsSync(path.join(SOURCE_DIR, "base16"))) {
    return path.join(SOURCE_DIR, "base16");
  }
  const entries = await readdir(SOURCE_DIR, { withFileTypes: true });
  const root = entries.find((entry) => entry.isDirectory());
  if (!root) throw new Error("Base16 source archive contained no root directory");
  return path.join(SOURCE_DIR, root.name, "base16");
}

async function generate(): Promise<void> {
  const root = await sourceRoot();
  const files = (await readdir(root)).filter((file) => /\.(yaml|yml)$/i.test(file)).sort();
  if (files.length === 0) throw new Error("Base16 source contains no YAML schemes");

  const palettes: Palette[] = [];
  const ids = new Set<string>();
  for (const file of files) {
    const raw = parse(await readFile(path.join(root, file), "utf8")) as Record<string, unknown>;
    const scheme = parseBase16Scheme(raw);
    const id = normalizeThemeId(scheme.slug ?? path.basename(file, path.extname(file)));
    if (ids.has(id)) throw new Error(`duplicate Base16 theme ID: ${id}`);
    ids.add(id);
    palettes.push(base16ToPalette(id, scheme));
  }

  const source = [
    "// Generated by scripts/fetch-base16-themes.ts — do not edit.",
    `// Source: ${SOURCE_URL}`,
    "import type { Palette } from \"../themes/palettes\";",
    "",
    `export const GENERATED_PALETTES: Palette[] = ${JSON.stringify(palettes, null, 2)};`,
    "",
  ].join("\n");
  await mkdir(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, source);
  writeFileSync(STATE_FILE, JSON.stringify({ revision: SOURCE_REVISION, count: palettes.length }, null, 2));
  log(`generated ${palettes.length} Base16 themes`);
}

async function main(): Promise<void> {
  if (isCurrent() && !process.argv.includes("--force")) {
    log("catalog is current — skipping");
    return;
  }
  await fetchSource();
  try {
    await generate();
  } finally {
    rmSync(CACHE_DIR, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error(`[themes] ${error instanceof Error ? error.message : error}`);
  process.exit(1);
});
