// UI fonts
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";

// Terminal fonts (Nerd Fonts, generated by `bun run fonts:fetch`)
import "./assets/nerd-fonts/nerd-fonts.css";
